allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - ws@8.21.0
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/utils@4.1.8'
  - vitest@4.1.8

packages: []
